# Базовый образ с Python
FROM python:3.11-slim

# Рабочая директория
WORKDIR /app

# Копируем код и requirements
COPY . /app
COPY requirements.txt /app

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Запуск бота
CMD ["python", "bot.py"]
