# Базовый образ с Python
FROM python:3.11-slim

# Рабочая директория
WORKDIR /app

# Копируем код и requirements
COPY . /app
COPY requirements.txt /app

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Устанавливаем ffmpeg для yt-dlp
RUN apt-get update && apt-get install -y ffmpeg

# Запуск бота
CMD ["python", "bot.py", "bots.py"]
